#
#  Copyright 2018 FLIR
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#

obj-y  += ec201.o
obj-y  += bootstate.o
obj-y  += cmd_recoverytrigger.o
