#
#  Copyright 2018 FLIR
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#

obj-y  += ec201.o
obj-y  += bootstate.o
obj-y  += chargeapp.o
obj-y  += pf1550.o
obj-y  += lc709203.o
obj-y  += cmd_recoverytrigger.o
obj-y  += cmd_setmac.o
obj-y  += ec201_splash.o
obj-y  += usbdcd.o
