#define LED_PGRM_INCREMENT (0 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (1 << LED_PGRM_RAMP_STEP_SHIFT) | (127 << LED_PGRM_RAMP_INCREMENT_SHIFT)
#define LED_PGRM_INCREMENT_STEP(x) (0 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (x << LED_PGRM_RAMP_STEP_SHIFT) | (127 << LED_PGRM_RAMP_INCREMENT_SHIFT)
#define LED_PGRM_DECREMENT (0 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (1 << LED_PGRM_RAMP_STEP_SHIFT) | (1 << LED_PGRM_RAMP_SIGN_SHIFT) | (127 << LED_PGRM_RAMP_INCREMENT_SHIFT)
#define LED_PGRM_DECREMENT_STEP(x) (0 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (x << LED_PGRM_RAMP_STEP_SHIFT) | (1 << LED_PGRM_RAMP_SIGN_SHIFT) | (127 << LED_PGRM_RAMP_INCREMENT_SHIFT)
#define LED_PGRM_WAIT(x) (1 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (((x * 10) / 156) << LED_PGRM_RAMP_STEP_SHIFT) | (0 << LED_PGRM_RAMP_INCREMENT_SHIFT);
#define LED_PGRM_WAIT_STEP(x) (1 << LED_PGRM_RAMP_PRESCALE_SHIFT) | (x << LED_PGRM_RAMP_STEP_SHIFT) | (0 << LED_PGRM_RAMP_INCREMENT_SHIFT);
#define LED_PGRM_STOP_NO_RESET 0xC000
#define LED_PGRM_GOTO_START 0x0000

#define LED_PGRM_WAIT_TRIGGER3  0xE200
#define LED_PGRM_SEND_TRIGGER12 0xE006